AWSTemplateFormatVersion: 2010-09-09
Description: "S3 Buckets creation for CSV raw data"

Parameters:
  CodeBucketName:
    Type: 'AWS::SSM::Parameter::Value<String>'
    Default: /vplk/codebucket
  CSVBucketName:
    Type: 'AWS::SSM::Parameter::Value<String>'
    Default: /vplk/rawbucket
  Service:
    Type: 'AWS::SSM::Parameter::Value<String>'
    Default: /vplk/servicetag
  Environment:
    Type: 'AWS::SSM::Parameter::Value<String>'
    Default: /vplk/env


Resources:

  CodeBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      BucketName:
        !Sub '${CodeBucketName}-${AWS::Region}-${Environment}'
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: True
        BlockPublicPolicy: True
        IgnorePublicAcls: True
        RestrictPublicBuckets: True
      VersioningConfiguration:
        Status: Enabled
      Tags:
        - Key: Service
          Value: !Ref Service
        - Key: Environment
          Value: !Ref Environment

  CSVBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      BucketName:
        !Sub '${CSVBucketName}-${AWS::Region}-${Environment}'
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: True
        BlockPublicPolicy: True
        IgnorePublicAcls: True
        RestrictPublicBuckets: True
      VersioningConfiguration:
        Status: Enabled
      Tags:
        - Key: Service
          Value: !Ref Service
        - Key: Environment
          Value: !Ref Environment

Outputs:
  CSVBucketName:
    Description: CSV Data bucket name
    Value: !Ref CSVBucketName