AWSTemplateFormatVersion: 2010-09-09
Description: "Create parameters in AWS SSM parameters store, will be used by other templates."


Resources:

  EnvTag:
    Type: AWS::SSM::Parameter
    Properties:
      Name: "/vplk/env"
      Type: "String"
      Value: "dev"
      Description: "Environment name."
      AllowedPattern: "^[a-zA-Z0-9.\\-_]+$"

  ServiceTag:
    Type: AWS::SSM::Parameter
    Properties:
      Name: "/vplk/servicetag"
      Type: "String"
      Value: "Vepolink"
      Description: "Service name."
      AllowedPattern: "^[a-zA-Z0-9.\\-_]+$"

  CodeBucketName:
    Type: AWS::SSM::Parameter
    Properties:
      Name: "/vplk/codebucket"
      Type: "String"
      Value: "vplk-code"
      Description: "CSV Data S3 bucket."
      AllowedPattern: "^[a-zA-Z0-9.\\-_]+$"

  CSVBucketName:
    Type: AWS::SSM::Parameter
    Properties:
      Name: "/vplk/rawbucket"
      Type: "String"
      Value: "vplk-raw-data"
      Description: "CSV Data S3 bucket."
      AllowedPattern: "^[a-zA-Z0-9.\\-_]+$"

  DeployRoleName:
    Type: AWS::SSM::Parameter
    Properties:
      Name: "/vplk/deployrole"
      Type: "String"
      Value: "vplk-deploy-role"
      Description: "Deployment role."
      AllowedPattern: "^[a-zA-Z0-9.\\-_]+$"

  IamPolicy:
    Type: AWS::SSM::Parameter
    Properties:
      Name: "/vplk/iampolicy"
      Type: "String"
      Value: "vplk-iam-policy"
      Description: "IAM specific policy"
      AllowedPattern: "^[a-zA-Z0-9.\\-_]+$"

  S3Policy:
    Type: AWS::SSM::Parameter
    Properties:
      Name: "/vplk/s3policy"
      Type: "String"
      Value: "vplk-s3-policy"
      Description: "S3 specific policy"
      AllowedPattern: "^[a-zA-Z0-9.\\-_]+$"